export const tr = {
  app: {
    name: "HÜsim",
    subtitle: "Maden Simülasyon Kontrol Sistemi",
    version: "v1.0",
  },
  nav: {
    dashboard: "Kontrol Paneli",
    scenarios: "Senaryolar",
    history: "Geçmiş",
    reports: "Raporlar",
  },
  weather: {
    title: "Hava Durumu Koşulları",
    subtitle: "Simülasyon parametreleri bu değerlere göre optimize edilecek",
    type: "Hava Tipi",
    types: {
      clear: "Açık",
      cloudy: "Bulutlu",
      rainy: "Yağmurlu",
      snowy: "Karlı",
      foggy: "Sisli",
      stormy: "Fırtınalı",
    },
    temperature: "Sıcaklık",
    wind: "Rüzgar Hızı",
    visibility: "Görüş Mesafesi",
    ground: "Zemin Durumu",
    grounds: {
      dry: "Kuru",
      wet: "Islak",
      muddy: "Çamurlu",
      snowy: "Karlı",
      icy: "Buzlu",
    },
    optimize: "Parametreleri Optimize Et",
    optimizing: "Hesaplanıyor...",
  },
  optimization: {
    title: "Optimizasyon Sonuçları",
    speed: "Hız Faktörü",
    braking: "Fren Mesafesi",
    visibility: "Görüş Alanı",
    safety: "Güvenlik Marjı",
    algorithm: "Önerilen Algoritma",
    risk: "Risk Seviyesi",
    notes: "Optimizasyon Notları",
    risks: {
      low: "Düşük",
      medium: "Orta",
      high: "Yüksek",
      critical: "Kritik",
    },
  },
  scenario: {
    title: "Senaryo Seçimi",
    select: "Senaryo Seç",
    run: "Simülasyonu Başlat",
    running: "Simülasyon Çalışıyor...",
    stop: "Durdur",
    batchRun: "Toplu Çalıştır",
    noScenario: "Henüz senaryo seçilmedi",
  },
  metrics: {
    title: "Simülasyon Metrikleri",
    safety: "Güvenlik",
    efficiency: "Verimlilik",
    smoothness: "Yumuşaklık",
    completion: "Tamamlanma",
    collisions: "Çarpışma",
    nearMisses: "Yakın Geçiş",
    riskScore: "Risk Skoru",
    completionTime: "Tamamlanma Süresi",
    pathEfficiency: "Güzergah Verimliliği",
    taskCompleted: "Görev Tamamlandı",
    taskFailed: "Görev Başarısız",
  },
  alerts: {
    title: "Uyarılar",
    none: "Aktif uyarı yok",
    collision: "⚠️ Çarpışma Riski",
    highSpeed: "⚡ Yüksek Hız Uyarısı",
    visibility: "🌫️ Düşük Görüş",
    ice: "🧊 Buzlanma Tehlikesi",
  },
  history: {
    title: "Geçmiş Simülasyonlar",
    date: "Tarih",
    scenario: "Senaryo",
    weather: "Hava Koşulu",
    result: "Sonuç",
    duration: "Süre",
    success: "Başarılı",
    failed: "Başarısız",
    noHistory: "Henüz simülasyon çalıştırılmadı",
  },
  report: {
    title: "Rapor Oluştur",
    generate: "PDF Rapor İndir",
    generating: "Rapor hazırlanıyor...",
    include: "Raporda yer alsın",
    metrics: "Metrikler",
    charts: "Grafikler",
    weather: "Hava Koşulları",
    comparison: "Algoritma Karşılaştırması",
  },
  status: {
    connected: "Bağlı",
    disconnected: "Bağlantı Kesildi",
    running: "Çalışıyor",
    idle: "Bekleniyor",
    error: "Hata",
  },
  scenarioGenerator: {
    title: "Yeni Senaryo Üret",
    intersectionType: "Kavşak Tipi",
    types: { T: "T Kavşak", cross: "Çapraz Kavşak", straight: "Düz Yol", complex: "Karmaşık Kavşak" },
    vehicleCount: "Araç Sayısı",
    difficulty: "Zorluk Seviyesi",
    difficulties: { easy: "Kolay", medium: "Orta", hard: "Zor", critical: "Kritik" },
    specialCondition: "Özel Koşul",
    conditions: { normal: "Normal", narrow: "Dar Yol", slope: "Eğimli Yol", blind: "Kör Kavşak" },
    scenarioName: "Senaryo Adı (opsiyonel)",
    generate: "Senaryo Üret",
    generating: "Üretiliyor...",
    success: "Senaryo oluşturuldu!",
  },
  compareMode: {
    title: "Karşılaştırma Modu",
    normal: "Normal Koşul",
    optimized: "Optimize Edilmiş",
    playBoth: "Senkron Oynat",
    pause: "Duraklat",
    risk: "Risk Skoru",
    avgSpeed: "Ort. Hız",
    collisions: "Çarpışma",
    comparing: "Karşılaştırılıyor...",
    selectScenario: "Senaryo seçin ve hava optimizasyonu yapın",
  },
  viewer: {
    ego: "EGO Kamyon",
    agent: "Ajan Araç",
    plannedRoute: "Planlanan Rota",
    conflictZone: "Çakışma Bölgesi",
    drivableArea: "Sürülebilir Alan",
    collision: "ÇARPIŞMA!",
    loading: "Senaryo yükleniyor...",
    empty: "Senaryo seçin veya simülasyon başlatın",
    controls: {
      play: "Oynat",
      pause: "Duraklat",
      rewind: "Başa Al",
      end: "Sona Al",
      stepBack: "Geri",
      stepForward: "İleri",
      speed: "Hız",
    },
  },
  scenarioFilter: {
    all: "Tümü",
    real: "Gerçek Veri",
    demo: "Demo",
    generated: "Üretilmiş",
    fleet: "Filo",
    loading: "Yükleniyor...",
    previewLoading: "Senaryo yükleniyor...",
    agentCount: "araç",
    seconds: "s",
  },
  loadSystem: {
    title: "Yük ve Eğim Parametreleri",
    vehicleType: "Araç Tipi",
    loadPercent: "Yük Yüzdesi",
    grade: "Yol Eğimi",
    empty: "Boş",
    halfLoaded: "Yarı Yüklü",
    fullLoaded: "Tam Yüklü",
    uphill: "Yokuş Yukarı",
    downhill: "Yokuş Aşağı",
    flat: "Düz",
    maxSpeed: "Maks. Hız",
    maxAccel: "Maks. İvme",
    brakeDistance: "Frenleme Mesafesi",
    totalWeight: "Toplam Ağırlık",
    loadEffect: "Yük Etkisi",
    gradeEffect: "Eğim Etkisi",
  },
  engineSystem: {
    title: "Motor Durumu",
    temperature: "Motor Sıcaklığı",
    status: {
      normal: "Normal",
      warning: "Uyarı",
      critical: "Kritik",
      emergency: "Acil Durdurma",
    },
    messages: {
      overheating: "Motor aşırı ısınıyor, hız kısıtlandı",
      emergency: "Kritik sıcaklık! Araç durduruluyor",
      cooling: "Motor soğuyor",
    },
  },
  eventZones: {
    title: "Saha Olayları",
    active: "Aktif Olaylar",
    addEvent: "Olay Ekle",
    quickAdd: "Hızlı Ekle",
    remainingTime: "Kalan Süre",
    clickToPlace: "Canvas'ta tıklayarak konumu seç",
    cancelPlacing: "İptal",
    randomEvent: "Rastgele Olay",
    noEvents: "Aktif olay yok",
    types: {
      kaya_dusme: "Kaya Düşmesi",
      yol_calismasi: "Yol Çalışması",
      su_birikintisi: "Su Birikintisi",
      toz_bulutu: "Toz Bulutu",
      diger_arac_arizasi: "Araç Arızası",
    },
    warnings: {
      entering: "Olay bölgesine giriliyor",
      speed_reduced: "Hız kısıtlandı",
      road_blocked: "Yol kapalı",
    },
  },
  dataset: {
    badge: "Gerçek Veri",
    telematicsSource: "Levin Telematics — 15,847 araç",
    maintenanceSource: "Vehicle Maintenance Telemetry",
    mineSource: "Open Pit Mine Object Detection",
    calibrated: "Kalibre Edilmiş",
    default: "Varsayılan",
    dataQuality: "Veri Kalitesi",
  },
  presentationMode: {
    title: "Sunum Modu",
    enter: "Sunum Moduna Gir",
    exit: "Normal Görünüme Dön",
    subtitle: "HÜsim — Maden Filo Simülasyon Kontrol Sistemi",
  },
  fleet: {
    title: "Filo Kontrol Paneli",
    vehicle: "Araç",
    status: "Durum",
    speed: "Hız",
    priority: "Öncelik",
    type: "Tip",
    statuses: {
      moving: "Hareket",
      waiting: "Bekliyor",
      slowing: "Yavaşlıyor",
      completed: "Tamamlandı",
      approaching: "Yaklaşıyor",
      bypassing: "Devre Dışı Geçiyor",
    },
    priorities: {
      "1": "Kritik",
      "2": "Yüksek",
      "3": "Normal",
      "4": "Düşük",
    },
    summary: {
      active: "Aktif",
      waiting: "Bekleyen",
      interventions: "Müdahale",
    },
    safetyZone: "Güvenli Mesafe",
    warningZone: "Uyarı Bölgesi",
    stopZone: "Dur Bölgesi",
    collisionPrevented: "Çarpışma önlendi",
    obstacleDetected: "Engel tespit edildi",
    routeRecalculating: "Rota yeniden hesaplanıyor...",
    intersectionControl: "Kavşak Yönetimi",
    convoyMode: "Konvoy Modu",
    waitingPoint: "Bekleme Noktası",
    priorityOrder: "Öncelik Sırası",
    noFleetData: "Filo verisi yok",
  },
}
